import type { RepoAnalysis } from "./types";

interface RepoInfo {
  owner: string;
  name: string;
  url: string;
  description: string | null;
  stars: number;
  forks: number;
  language: string | null;
  topics: string[];
}

export function analysisToMarkdown(
  repo: RepoInfo,
  analysis: RepoAnalysis
): string {
  const lines: string[] = [
    `# RepoMentor Guide: ${repo.owner}/${repo.name}`,
    "",
    `> Generated by [RepoMentor](https://github.com) · [${repo.url}](${repo.url})`,
    "",
    repo.description ? `${repo.description}\n` : "",
    `**Stars:** ${repo.stars.toLocaleString()} · **Forks:** ${repo.forks.toLocaleString()} · **Language:** ${repo.language ?? "N/A"} · **Beginner Score:** ${analysis.beginnerFriendlyScore}/10`,
    "",
    repo.topics.length ? `**Topics:** ${repo.topics.join(", ")}\n` : "",
    "---",
    "",
    "## Project Summary",
    "",
    analysis.summary,
    "",
    "## Tech Stack",
    "",
    ...analysis.techStack.map(
      (t) =>
        `- **${t.name}** (${t.category}) — ${t.confidence} confidence — ${t.evidence}`
    ),
    "",
    "## Setup Instructions",
    "",
    ...analysis.setupInstructions.map((s, i) => `${i + 1}. \`${s}\``),
    "",
    "## Folder Guide",
    "",
    ...analysis.folderGuide.flatMap((f) => [
      `### \`${f.path}\``,
      f.purpose,
      f.keyFiles.length ? `**Key files:** ${f.keyFiles.map((k) => `\`${k}\``).join(", ")}` : "",
      f.beginnerTip ? `> 💡 ${f.beginnerTip}` : "",
      "",
    ]),
    "## Good First Issues",
    "",
    ...(analysis.recommendedIssues.length
      ? analysis.recommendedIssues.flatMap((i) => [
          `### #${i.issueNumber}: ${i.title}`,
          `- **Difficulty:** ${i.difficulty}`,
          `- **Estimated:** ${i.estimatedHours}`,
          `- **URL:** ${i.url}`,
          `- **Why:** ${i.whyGoodFirst}`,
          `- **Skills:** ${i.skillsNeeded.join(", ")}`,
          "",
        ])
      : ["No recommended issues found.\n"]),
    "## Learning Path",
    "",
    ...analysis.learningPath.flatMap((s) => [
      `### Step ${s.step}: ${s.title} (${s.estimatedTime})`,
      s.description,
      s.resources.length ? `**Resources:** ${s.resources.join(", ")}` : "",
      "",
    ]),
    "## PR Checklist",
    "",
    ...analysis.prChecklist.map((c) => `- [ ] ${c.item} _(${c.category})_`),
    "",
    "## Test Suggestions",
    "",
    ...analysis.testSuggestions.map((t) => `- ${t}`),
    "",
    "## Contribution Tips",
    "",
    ...analysis.contributionTips.map((t) => `- ${t}`),
    "",
    "---",
    "",
    "_Exported from RepoMentor_",
  ];

  return lines.filter((l) => l !== undefined).join("\n");
}

export function downloadMarkdown(
  repo: RepoInfo,
  analysis: RepoAnalysis
): void {
  const md = analysisToMarkdown(repo, analysis);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `repomentor-${repo.owner}-${repo.name}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function printAsPdf(): void {
  window.print();
}
